# Copyright (C) 2017 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the License);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_PACKAGES += \
                    vendor.nvidia.hardware.graphics.composer@1.0-service \
                    vendor.nvidia.hardware.graphics.composer@1.0 \
                    vendor.nvidia.hardware.graphics.composer@1.0-impl \
                    libnvhwcomposer \
                    libnvblit \
                    libnvddk_vic \
                    libnvos \
                    libnvrm \
                    libnvcolorutil \
                    libnvrm_graphics \
                    libnvgr \
                    libnvrm_gpu \
                    libnvdc \
                    libnvimp \
                    vendor.nvidia.hardware.graphics.display@1.0 \
                    libtlk_secure_hdcp_up \
                    libtsechdcp \
                    vendor.nvidia.hardware.graphics.display@1.0-impl \
                    audio.primary.tegra_32 \
                    libnvos_32 \
                    libnvoice_32 \
                    libnvaudiofx_32 \
                    camera.tegra_32 \
                    libnvddk_2d_v2_32 \
                    libnvrm_32 \
                    libnvcolorutil_32 \
                    libnvrm_graphics_32 \
                    libnvddk_vic_32 \
                    libnvgr_32 \
                    libnvmm_utils_32 \
                    libnvavp_32 \
                    libnvtvmr_32 \
                    libnvdc_32 \
                    libnvimp_32 \
                    libnvcam_imageencoder_32 \
                    libnvmm_32 \
                    libnvmm_camera_v3_32 \
                    libnvodm_imager_32 \
                    libnvcamerautils_32 \
                    libnvcamlog_32 \
                    libnvcamv4l2_32 \
                    libnvisp_v3_32 \
                    libnvvicsi_v3_32 \
                    libnvcspline_32 \
                    libcuda_32 \
                    libnvphs_32 \
                    vendor.nvidia.hardware.phs@1.0_32 \
                    libnvrm_gpu_32 \
                    libnvidia-fatbinaryloader_32 \
                    libnvisp_32 \
                    libnvscf_32 \
                    libnvfnet_32 \
                    libnvfnetstorehdfx_32 \
                    libnvfnetstoredefog_32 \
                    gatekeeper.tlk.tegra_32 \
                    gralloc.tegra_32 \
                    libnvblit_32 \
                    hdmi_cec.tegra_32 \
                    vulkan.tegra_32 \
                    hdmi_cec.tegra \
                    gralloc.tegra \
                    gatekeeper.tlk.tegra \
                    keystore.v0.tegra \
                    keystore.v1.tegra \
                    vulkan.tegra \
                    libril-icera_32 \
                    icera-switcherd_32 \
                    downloader_32 \
                    sensors.t210ref.api_v1.4.mpl530.nvs \
                    libsensors.hal.nvs \
                    libsensors.hal-drivers.nvs \
                    libsensors.fusion.mpl530.nvs \
                    libmplmpu \
                    libmllite \
                    eks2_client \
                    tlk_daemon \
                    ss_status \
                    libtsec_wrapper_32 \
                    libtsec_wrapper \
                    libEGL_tegra_32 \
                    libnvglsi_32 \
                    libnvrmapi_tegra_32 \
                    libnvcpl_32 \
                    libGLESv1_CM_tegra_32 \
                    libglcore_32 \
                    libnvrmvkif_32 \
                    libnvidia-glvkspirv_32 \
                    libGLESv2_tegra_32 \
                    libnvwsi_32 \
                    libEGL_tegra \
                    libnvglsi \
                    libnvrmapi_tegra \
                    libnvcpl \
                    libnvphs \
                    vendor.nvidia.hardware.phs@1.0 \
                    libGLESv1_CM_tegra \
                    libglcore \
                    libnvrmvkif \
                    libnvidia-glvkspirv \
                    libGLESv2_tegra \
                    libnvwsi \
                    glgps_nvidiaTegra2android \
                    gps.brcm \
                    libnvmm_audio_32 \
                    libnvmm_msaudio_32 \
                    libnvmm_parser_32 \
                    libnvmm_contentpipe_32 \
                    libnvmm_writer_32 \
                    libnvmmlite_audio_32 \
                    libnvmmlite_utils_32 \
                    libnvmmlite_32 \
                    libnvmmlite_image_32 \
                    libnvparser_32 \
                    libnvmmlite_video_32 \
                    libnvtnr_32 \
                    libnvmedia_32 \
                    libnvmm_parser \
                    libnvmm_utils \
                    libnvavp \
                    libnvmm_contentpipe \
                    libnvmmlite_image \
                    libnvmmlite_utils \
                    libnvmmlite \
                    libnvparser \
                    libnvtvmr \
                    libnvddk_2d_v2 \
                    libnvmmlite_video \
                    libnvtnr \
                    libnvmedia \
                    libcuda \
                    libnvidia-fatbinaryloader \
                    libnvomx_32 \
                    libnvomxadaptor_32 \
                    libnvomxilclient_32 \
                    libnvomx \
                    vendor.nvidia.hardware.power@1.0_vendor \
                    libnvmm \
                    libnvvpp \
                    libnvomxadaptor \
                    rm_ts_server_32 \
                    librm_ts_service_32 \
                    ts.default_32 \
                    librm31080_32 \
                    touch_para_10_32 \
                    libcuda_32 \
                    libcuda \
                    pbc2 \
                    pbc.tegra \
                    pbc.tegra_32
